$(function(){
    var items = {
    'Absorb Bulb': ' Gear Station, PWT, Wild Roserade 1%, Wild Roselia 1%',
    'Adamant Orb': ' Dragonspiral Tower',
    'Air Balloon': ' Gear Station, PWT, Wild Drifblim 1%',
    'Apicot Berry': ' Join Avenue',
    'Big Root': ' Driftveil City, Wild Cradily 5%, Wild Lileep 5%',
    'Berry Juice': ' Join Avenue, Wild Shuckle 100%',
    'Binding Band': ' Gear Station, PWT',
    'Power Anklet': ' Gear Station, PWT',
    'Power Bracer': ' Gear Station, PWT',
    'Power Belt': ' Gear Station, PWT',
    'Power Weight': ' Gear Station, PWT',
    'Power Lens': ' Gear Station, PWT',
    'Power Band': ' Gear Station, PWT',
    'Black Belt': ' Icirrus City, Wild Throh 5%, Wild Sawk 5%',
    'Black Sludge': ' Castelia Sewers, Wild Grimer 5%, Wild Muk 50%, Wild Croagunk 5%, Wild Toxicroak 5%, Wild Trubbish 5%, Wild Garbodor 50%',
    'Black Glasses': ' Desert Resort',
    'Charcoal': ' Castelia City',
    'Deep Sea Scale': ' White Forest, Join Avenue, Wild Chinchou 5%, Wild Lanturn 5%, Wild Gorebyss 5%, Wild Relicanth 5%',
    'Deep Sea Tooth': ' White Forest, Join Avenue, Wild Carvanha 5%, Wild Sharpedo 5%, Wild Huntail 5%, Wild Basculin 5%',
    'Choice Band': ' Gear Station, PWT',
    'Choice Specs': ' Gear Station, PWT',
    'Choice Scarf': ' Gear Station, PWT',
    'Damp Rock': ' Route 8',
    'Draco Plate': ' Undella Bay',
    'Dragon Fang': ' Dragonspiral Tower, Wild Bagon 5%, Wild Shelgon 5%, Wild Salamence 5%, Wild Druddigon 5%',
    'Dread Plate': ' Abyssal Ruins',
    'Earth Plate': ' Abyssal Ruins',
    'Everstone': ' Castelia City, Wild Boldore 50%, Wild Roggenrola 50%, Wild Gigalith 50%, Wild Geodude 5%, Wild Graveler 5%, Wild Golem 5%',
    'Eviolite': ' Castelia City',
    'Expert Belt': ' Driftveil City, Route 19 (Hidden), Wild Throh 1%, Wild Sawk 1%',
    'Fist Plate': ' Abyssal Ruins',
    'Flame Orb': ' Gear Station, PWT, Wild Heatmor 1%',
    'Flame Plate': ' Abyssal Ruins',
    'Focus Sash': ' Gear Station, PWT',
    'Heat Rock': ' Route 8',
    'Icicle Plate': ' Abyssal Ruins',
    'Icy Rock': ' Route 8',
    'Insect Plate': ' Abyssal Ruins',
    'Iron Plate': ' Abyssal Ruins',
    'King\'s Rock': ' Route 13, Wild Poliwhirl 5%, Wild Poliwrath 5%, Wild Slowbro 5%, Wild Politoed 5%, Wild Slowking 5%, Wild Hariyama 5%',
    'Leftovers': ' Castelia Sewers, Wild Snorlax 100%, Wild Munchlax 100%',
    'Life Orb': ' Gear Station, PWT',
    'Light Clay': ' Wild Golett 5%, Wild Golurk 5%',
    'Meadow Plate': ' Abyssal Ruins',
    'Mental Herb': ' Wild Sewaddle 5%, Wild Swadloon 5%, Wild Leavanny 5%',
    'Metal Coat': ' Clay Tunnel, Chargestone Cave, Wild Magnemite 5%, Wild Magneton 5%, Wild Steelix 5%, Wild Beldum 5%, Wild Metang 5%, Wild Metagross 5%, Wild Bronzor 5%, Wild Bronzong 5%, Wild Magnezone 5%',
    'Mind Plate': ' Abyssal Ruins',
    'Miracle Seed': ' Castelia City, Wild Cherubi 5%, Wild Cherrim 5%, Wild Maractus 5%',
    'Mystic Water': ' Route 4, Castelia City, Wild Castform 100%',
    'Never-Melt Ice': ' Dragonspiral Tower (Winter), Wild Snover 5%, Wild Abomasnow 5%, Wild Cryogonal 5%',
    'Poison Barb': ' Route 22, Wild Beedrill 5%, Wild Tentacool 5%, Wild Tentacruel 5%, Wild Qwilfish 5%, Wild Roselia 5%, Wild Budew 5%, Wild Roserade 5%, Wild Vespiquen 5%, Wild Skorupi 5%, Wild Drapion 5%, Wild Venipede 5%, Wild Whirlipede 5%, Wild Scolipede 5%',
    'Quick Claw': ' Skyarrow Bridge, Wild Sandshrew 5%, Wild Sandslash 5%, Wild Meowth 5%, Wild Persian 5%, Wild Sneasel 5%, Wild Zangoose 5%, Wild Weavile 5%',
    'Razor Fang': ' Route 11',
    'Odd Incense': ' Driftveil City',
    'Rock Incense': ' Driftveil City',
    'Wave Incense': ' Driftveil City',
    'Wise Glasses': ' Gear Station, PWT',
    'Sea Incense': ' Driftveil City',
    'Sharp Beak': ' Mistralton City, Wild Fearow 5%, Wild Doduo 5%, Wild Dodrio 5%',
    'Rose Incense': ' Driftveil City',
    'Silver Powder': ' Pinwheel Forest, Wild Butterfree 5%, Wild Masquerain 5%, Wild Wormadam 5%, Wild Mothim 5%, Wild Volcarona 100%',
    'Red Card': ' Gear Station, PWT',
    'Rocky Helmet': ' Relic Passage, PWT',
    'Shell Bell': ' Driftveil City',
    'Silk Scarf': ' Virbank Complex',
    'SilverPowder': ' Wild Butterfree 5%, Wild Masquerain 5%, Wild Wormadam 5%, Wild Mothim 5%, Wild Volcarona 100%',
    'Sky Plate': ' Abyssal Ruins',
    'Smooth Rock': ' Route 8',
    'Stick': ' Route 13, Wild Farfetch\'d 5% ',
    'Soft Sand': ' Desert Resort, Wild Diglett 5%, Wild Dugtrio 5%, Wild Trapinch 5%, Wild Stunfisk 5%',
    'Splash Plate': ' Abyssal Ruins',
    'Spell Tag': ' Celestial Tower, Wild Shuppet 5%, Wild Banette 5%, Wild Yamask 5%, Wild Cofagrigus 5%',
    'Spooky Plate': ' Abyssal Ruins',
    'Stone Plate': ' Abyssal Ruins',
    'Thick Club': ' Wild Cubone 5%, Wild Marowak 5%',
    'Twisted Spoon': ' Castelia Sewers, Wild Abra 5%, Wild Kadabra 5%, Wild Alakazam 5%',
    'Toxic Orb': ' Gear Station, PWT, Wild Muk 1%',
    'Toxic Plate': ' Abyssal Ruins',
    'Zap Plate': ' Abyssal Ruins',
    'Babiri Berry': ' Join Avenue, Wild Snorunt 5%, Wild Glalie 5%, Wild Froslass 5%',
'Belue Berry': ' Join Avenue',
'Charti Berry': ' Join Avenue, Wild Taillow 5%, Wild Swellow 5%',
'Chesto Berry': ' Join Avenue, Wild Whismur 5%, Wild Loudred 5%, Wild Exploud 5%, Wild Spinda 5%, Wild Minccino 50%, Wild Cinccino 50%',
'Chilan Berry': ' Join Avenue',
'Chople Berry': ' Join Avenue',
'Coba Berry': ' Join Avenue',
'Colbur Berry': ' Join Avenue, Wild Chimecho 5%, Wild Chingling 5%',
'Durin Berry': ' Join Avenue', 
'Griseous Orb': ' Dragonspiral Tower',
'Lustrous Orb': ' Dragonspiral Tower', 
'Macho Brace': ' Route 16', 
'Magnet': ' Chargestone Cave', 
'Muscle Band': ' Gear Station, PWT', 
'Hard Stone': ' Relic Passage, Join Avenue, Wild Corsola 5%, Wild Nosepass 5%, Wild Aron 5%, Wild Lairon 5%, Wild Aggron 5%, Wild Probopass 5%, Wild Roggenrola 5%, Wild Boldore 5%, Wild Gigalith 5%, Wild Dwebble 5%, Wild Crustle 5%', 
'Ganlon Berry': ' Join Avenue', 
'Haban Berry': ' Join Avenue, Wild Gible 5%, Wild Gabite 5%, Wild Garchomp 5%', 
'Kasib Berry': ' Join Avenue, Wild Duskull 5%, Wild Dusclops 5%, Wild Dusknoir 5%', 
'Kebia Berry': ' Join Avenue, Wild Shroomish 5%, Wild Breloom 5%', 
'Leppa Berry': ' Join Avenue, Wild Clefairy 50%, Wild Clefable 50%, Wild Cleffa 50%', 
'Liechi Berry': ' Join Avenue', 
'Lum Berry': ' Join Avenue, Wild Mew 100%, Wild Celebi 100%, Wild Shaymin 100%', 
'Occa Berry': ' Join Avenue, Wild Mawile 5%, Wild Pansage 5%, Wild Simisage 5%', 
'Metal Powder': ' Route 13, Wild Ditto 5%', 
'Iron Ball': ' Gear Station, PWT', 
'Light Ball': ' Wild Pikachu 5%', 
'Lagging Tail': ' Wild Slowpoke 5%, Wild Lickitung 5%, Wild Lickilicky 5%', 
'Oran Berry': ' Join Avenue Wild Sentret 5%, Wild Furret 50%, Wild Zigzagoon 5%, Wild Linoone 50%, Wild Bibarel 50%, Wild Pansage 50%, Wild Simisage 50%, Wild Pansear 50%, Wild Simisear 50%, Wild Panpour 50%, Wild Simipour 50%, Wild Audino 50%', 
'Passho Berry': ' Join Avenue, Wild Phanpy 5%, Wild Donphan 5%, Wild Pansear 5%, Wild Simisear 5%', 
'Payapa Berry': ' Join Avenue, Wild Mankey 5%, Wild Primeape 5%', 
'Rawst Berry': ' Join Avenue, Wild Vulpix 100%, Wild Ninetales 100%, Wild Growlithe 50%, Wild Arcanine 50%, Wild Numel 100%, Wild Camerupt 100%, Wild Darumaka 50%, Wild Darmanitan 50%', 
'Rindo Berry': ' Join Avenue, Wild Finneon 5%, Wild Lumineon 5%, Wild Panpour 5%, Wild Simipour 5%', 
'Salac Berry': ' Join Avenue', 
'Shuca Berry': ' Join Avenue, Wild Ponyta 5%, Wild Rapidash 5%', 
'Sitrus Berry': ' Join Avenue, Wild Furret 5%, Wild Linoone 5%, Wild Bibarel 5%, Wild Audino 5%', 
'Tanga Berry': ' Join Avenue', 
'Wacan Berry': ' Join Avenue', 
'Watmel Berry': ' Join Avenue', 
'Yache Berry': ' Join Avenue, Wild Starly 5%, Wild Staravia 5%, Wild Staraptor 5%' 
        
    };
    
    var moves = {
    	'Hone Claws':' TM01 Victory Road',
	'Dragon Claw':' TM02 Dragonspiral Tower',
	'Psyshock':' TM03 Giant Chasm',
	'Calm Mind':' TM04 Striaton City Poke Mart',
	'Roar':' TM05 Route 23',
	'Toxic':' TM06 Seaside Cave',
	'Hail':' TM07 Mistralton City Poke Mart',
	'Bulk Up':' TM08 Striaton City Poke Mart',
	'Venoshock':' TM09 Defeat Roxie',
	'Hidden Power':' TM10 Battle Subway, PWT',
	'Sunny Day':' TM11 Mistralton City Poke Mart',
	'Taunt':' TM12 Route 23',
	'Ice Beam':' TM13 Giant Chasm',
	'Blizzard':' TM14 Lacunosa Town Poke Mart',
	'Hyper Beam':' TM15 Route 9 Dept. Store',
	'Light Screen':' TM16 Nimbasa City Poke Mart',
	'Protect':' TM17 Battle Subway, PWT',
	'Rain Dance':' TM18 Mistralton City Poke Mart',
	'Telekinesis':' TM19 Route 18',
	'Safeguard':' TM20 Battle Subway, PWT',
	'Frustration':' TM21 Floccesy Ranch',
	'SolarBeam':' TM22 Pinwheel Forest',
	'Smack Down':' TM23 Battle Subway, PWT',
	'Thunderbolt':' TM24 Victory Road',
	'Thunder':' TM25 Lacunosa Town Poke Mart',
	'Earthquake':' TM26 Route 15',
	'Return':' TM2 Aspertia City',
	'Dig':' TM28 Route 4',
	'Psychic':' TM29 Route 13',
	'Shadow Ball':' TM30 Reversal Mountain',
	'Brick Break':' TM31 Battle Subway, PWT',
	'Double Team':' TM31 Battle Subway, PWT',
	'Reflect':' TM33 Nimbasa City Poke Mart',
	'Sludge Wave':' TM34 Battle Subway, PWT',
	'Flamethrower':' TM35 Route 23',
	'Sludge Bomb':' TM36 Route 8',
	'Sandstorm':' TM37 Mistralton City Poke Mart',
	'Fire Blast':' TM38 Lacunosa Town Poke Mart',
	'Rock Tomb':' TM39 Relic Castle',
	'Aerial Ace':' TM40 Mistralton City',
	'Torment':' TM41 Castelia Sewers',
	'Facade':' TM42 Humilau City',
	'Flame Charge':' TM43 Tubeline Bridge',
	'Rest':' TM44 Castelia City',
	'Attract':' TM45 Castelia City',
	'Thief':' TM46 Virbank Complex',
	'Low Sweep':' TM47 Wellspring Cave',
	'Round':' TM48 Battle Subway, PWT',
	'Echoed Voice':' TM49 Nimbasa City Musical Hall',
	'Overheat':' TM50 N\'s Castle',
	'Ally Switch':' TM51 Battle Subway, PWT',
	'Focus Blast':' TM52 Wellspring Cave',
	'Energy Ball':' TM53 Aspertia City',
	'False Swipe':' TM54 Reversal Mountain',
	'Scald':' TM55 Defeat Marlon',
	'Fling':' TM56 Route 6',
	'Charge Beam':' TM57 Lentimas Town',
	'Sky Drop':' TM58 Mistralton City',
	'Incinerate':' TM59 Battle Subway, PWT',
	'Quash':' TM60 Battle Subway, PWT',
	'Will-O-Wisp':' TM61 Celestial Tower',
	'Acrobatics':' TM62 Defeat Skyla',
	'Embargo':' TM63 Driftveil City Market',
	'Explosion':' TM64 Battle Subway, PWT',
	'Shadow Claw':' TM65 Celestial Tower',
	'Payback':' TM66 Route 16',
	'Retaliate':' TM67 Plasma Frigate',
	'Giga Impact':' TM68 Route 9 Dept. Store',
	'Rock Polish':' TM69 Reversal Mountain',
	'Flash':' TM70 Castelia City',
	'Stone Edge':' TM71 Twist Mountain',
	'Volt Switch':' TM72 Defeat Elesa',
	'Thunder Wave':' TM73 Nimbasa City Poke Mart',
	'Gyro Ball':' TM74 Nimbasa City Poke Mart',
	'Swords Dance':' TM75 Battle Subway, PWT',
	'Struggle Bug':' TM76 Defeat Burgh',
	'Psych Up':' TM77 Battle Subway, PWT',
	'Bulldoze':' TM78 Defeat Clay',
	'Frost Breath':' TM79 Battle Subway, PWT',
	'Rock Slide':' TM80 Mistralton Cave',
	'X-Scissor':' TM81 Route 7',
	'Dragon Tail':' TM82 Defeat Drayden',
	'Work Up':' TM83 Defeat Cheren',
	'Poison Jab':' TM84 Moor of Icirrus',
	'Dream Eater':' TM85 Dreamyard',
	'Grass Knot':' TM86 Pinwheel Forest',
	'Swagger':' TM87 Battle Subway, PWT',
	'Pluck':' TM88 Battle Subway, PWT',
	'U-Turn':' TM89 Battle Subway, PWT',
	'Substitute':' TM90 Twist Mountain',
	'Flash Cannon':' TM91 Twist Mountain',
	'Trick Room':' TM92 Abundant Shrine',
	'Wild Charge':' TM93 Victory Road',
	'Rock Smash':' TM94 Virbank Complex',
	'Snarl':' TM95 Lostlorn Forest',
	'Grass Pledge':' PWT Move Tutor',
	'Fire Pledge':' PWT Move Tutor',
	'Water Pledge':' PWT Move Tutor',
	'Frenzy Plant':' PWT Move Tutor',
	'Blast Burn':' PWT Move Tutor',
	'Hydro Cannon':' PWT Move Tutor',
	',Covet':' Driftveil City Move Tutor',
	'Bug Bite':' Driftveil City Move Tutor',
	'Drill Run':' Driftveil City Move Tutor',
	'Bounce':' Driftveil City Move Tutor',
	'Signal Beam':' Driftveil City Move Tutor',
	'Iron Head':' Driftveil City Move Tutor',
	'Super Fang':' Driftveil City Move Tutor',
	'Uproar':' Driftveil City Move Tutor',
	'Seed Bomb':' Driftveil City Move Tutor',
	'Dual Chop':' Driftveil City Move Tutor',
	'Low Kick':' Driftveil City Move Tutor',
	'Gunk Shot':' Driftveil City Move Tutor',
	'Thunder Punch':' Driftveil City Move Tutor',
	'Fire Punch':' Driftveil City Move Tutor',
	'Ice Punch':' Driftveil City Move Tutor',
	'Last Resort':' Lentimas Town Move Tutor',
	'Iron Defense':' Lentimas Town Move Tutor',
	'Magnet Rise':' Lentimas Town Move Tutor',
	'Magic Coat':' Lentimas Town Move Tutor',
	'Block':' Lentimas Town Move Tutor',
	'Hyper Voice':' Lentimas Town Move Tutor',
	'Electroweb':' Lentimas Town Move Tutor',
	'Icy Wind':' Lentimas Town Move Tutor',
	'Iron Tail':' Lentimas Town Move Tutor',
	'Aqua Tail':' Lentimas Town Move Tutor',
	'Earth Power':' Lentimas Town Move Tutor',
	'Zen Headbutt':' Lentimas Town Move Tutor',
	'Foul Play':' Lentimas Town Move Tutor',
	'Superpower':' Lentimas Town Move Tutor',
	'Gravity':' Lentimas Town Move Tutor',
	'Dragon Pulse':' Lentimas Town Move Tutor',
	'Dark Pulse':' Lentimas Town Move Tutor',
	'Draco Meteor':' Opelucid City Move Tutor',
	'Bind':' Humilau City Move Tutor',
	'Snore':' Humilau City Move Tutor',
	'Heal Bell':' Humilau City Move Tutor',
	'Knock Off':' Humilau City Move Tutor',
	'Synthesis':' Humilau City Move Tutor',
	'Roost':' Humilau City Move Tutor',
	'Sky Attack':' Humilau City Move Tutor',
	'Role Play':' Humilau City Move Tutor',
	'Heat Wave':' Humilau City Move Tutor',
	'Giga Drain':' Humilau City Move Tutor',
	'Drain Punch':' Humilau City Move Tutor',
	'Pain Split':' Humilau City Move Tutor',
	'Tailwind':' Humilau City Move Tutor',
	'Worry Seed':' Nacrene City Move Tutor',
	'Gastro Acid':' Nacrene City Move Tutor',
	'Helping Hand':' Nacrene City Move Tutor',
	'After You':' Nacrene City Move Tutor',
	'Magic Room':' Nacrene City Move Tutor',
	'Wonder Room':' Nacrene City Move Tutor',
	'Spite':' Nacrene City Move Tutor',
	'Recycle':' Nacrene City Move Tutor',
	'Trick':' Nacrene City Move Tutor',
	'Stealth Rock':' Nacrene City Move Tutor',
	'Outrage':' Nacrene City Move Tutor',
	'Endeavor':' Nacrene City Move Tutor',
	'Sleep Talk':' Nacrene City Move Tutor',
	'Skill Swap':' Nacrene City Move Tutor',
	'Snatch':' Nacrene City Move Tutor'
    };
    
    var locations = {
    	'Snivy':' Starter',
	'Servine':' Evolve Snivy',
	'Serperior':' Evolve Servine',
	'Tepig':' Starter',
	'Pignite':' Evolve Tepig',
	'Emboar':' Evolve Pignite',
	'Oshawott':' Starter',
	'Dewott':' Evolve Oshawott',
	'Samurott':' Evovle Dewott',
	'Lillipup':' Floccesy Ranch Grass 40%',
	'Patrat':' Route 19 Grass 50%, Route 19 Shaking Grass 100%, Virbank Complex Outside Grass 35%',
	'Watchog':' Route 1 Grass & Dark Grass 40%, Route 2 Grass 30%',
	'Purrloin':' Route 19 Grass 50%',
	'Liepard':' Dreamyard Grass & Dark Grass 25%, Route 2 Grass 20%, Route 5 Grass & Dark Grass 20%',
	'Pidove':' Virbank Complex Outside Grass 35%, Route 20 Autumn, Spring, Winter Grass & Dark Grass 25%',
	'Tranquill':' Victory Road Outside Grass & Dark Grass 80%, Dragonspiral Tower Grass 35 %, Routes 3 & 7 Grass & Dark Grass 30%',
	'Unfezant':' Routes 3, 6, 7, & 12 Shaking Grass 5%, Dragonspiral Tower Shaking Grass 5%',
	'Sewaddle':' Route 20 Grass 35%',
	'Swadloon':' Pinwheel & Lostlorn Forest Grass & Dark Grass 25%',
	'Leavanny':' Routes 6 & 12 Shaking Grass 5%, Lostlorn Forest Shaking Grass 5%',
	'Sunkern':' Route 20 Summer Grass & Dark Grass 26%',
	'Sunflora':' Evolve Sunkern',
	'Herdier':' Route 1 Dark Grass 39%, Route 1 Grass 50%',
	'Stoutland':' Route 1, 2, 3 Shaking Grass 5%, P2 Laboratory Shaking Grass 5%'
    };
        
    $('.Pokemon').keypress(function(event){
        if(event.which == 13){
            $('.go').click();
        }
    });
    
    $('.go').click(function(){
        var poke = $('.Pokemon').val();
        var hp = ($('.hp').val() && $('.hp').val() !== '0' ? ' Level up holding Power Weight against Stunfisk for a total of 6 HP EVs per level. Level up holding Power Weight against Victini for a total of 7 HP EVs per level.' : ''); 
        var attack = ($('.atk').val() && $('.atk').val() !== '0' ? ' Level up holding Power Bracer against Tranquill, Sawsbuck, Druddigon, or Beartic for a total of 6 Attack EVs per level. Level up holding Power Bracer against Patrat, Lillipup, Mienfoo, or Golett for a total of 5 Attack EVs per level.': '');
        var defense = ($('.def').val() && $('def').val() !== '0' ? ' Level up holding Power Belt against Roggenrola, Onix, Sewaddle, or Venipede for a total of 5 Defense EVs per level. Level up holding Power Belt against Sandslash or Cofagrigus for a total of 6 Defense EVs per level.': '');
        var spattack = ($('.spatk').val() && $('.spatk').val() !== '0' ? ' Level up holding Power Lens against Litwick or Elgyem for a total of 5 Special Attack EVs per level. ': '');
        var spdefense = ($('.spdef').val() && $('.spdef').val() !== '0' ? ' Level up holding Power Band against Frillish for a total of 5 Special Defense EVs per level. Level up holding Power Band against Claydol for a total of 6 Special Defense EVs per level. ': '');
        var speed = ($('.spe').val() && $('.spe').val() !== '0' ? ' Level up holding Power Anklet against Basculin for a total of 5 Speed EVs per level.': '');
        
        $('.result-container').html('<span class="result">How to breed the perfect ' + poke + '!</span>' +
        '<p class="moveinfo">' + poke + ': Found at ' + locations[poke] + </p>' +
        '<p class="moveinfo">' + $('.item :selected').text() +': Found at ' + items[$('.item :selected').text()] + '</p>' +
        '<p class="moveinfo">EVs: ' + hp + attack + defense + spattack + spdefense + speed + '</p>' +
        '<p class="moveinfo">' + $('.nature :selected').text() + ' Nature: Breed with a ' + $('.nature :selected').text() + ' nature Ditto holding an Everstone </p>' +
        '<p class="moveinfo">' + $('.move-1 :selected').text() + ': ' + moves[$('.move-1 :selected').text()] + '</p>' +
        '<p class="moveinfo">' + $('.move-2 :selected').text() + ': ' + moves[$('.move-2 :selected').text()] + '</p>' +
        '<p class="moveinfo">' + $('.move-3 :selected').text() + ': ' + moves[$('.move-3 :selected').text()] + '</p>' +
        '<p class="moveinfo">' + $('.move-4 :selected').text() + ': ' + moves[$('.move-4 :selected').text()] + '</p>'
        );
  });
  
			// var request = new XMLHttpRequest();
			// request.open("GET", "http://pokeapi.co/api/v1/pokemon/245/", false); // synchronous request
			// request.send(null);
			// var parse = JSON.parse(request.responseText);
			// document.write(parse);
				
});
