$(function(){
    var items = {
	'Absorb Bulb': ' Gear Station, PWT, Wild Roserade 1%, Wild Roselia 1%',
	'Adamant Orb': ' Dragonspiral Tower',
	'Air Balloon': ' Gear Station, PWT, Wild Drifblim 1%',
	'Apicot Berry': ' Join Avenue',
	'Big Root': ' Driftveil City, Wild Cradily 5%, Wild Lileep 5%',
	'Berry Juice': ' Join Avenue, Wild Shuckle 100%',
	'Binding Band': ' Gear Station, PWT',
	'Power Anklet': ' Gear Station, PWT',
	'Power Bracer': ' Gear Station, PWT',
	'Power Belt': ' Gear Station, PWT',
	'Power Weight': ' Gear Station, PWT',
	'Power Lens': ' Gear Station, PWT',
	'Power Band': ' Gear Station, PWT',
	'Black Belt': ' Icirrus City, Wild Throh 5%, Wild Sawk 5%',
	'Black Sludge': ' Castelia Sewers, Wild Grimer 5%, Wild Muk 50%, Wild Croagunk 5%, Wild Toxicroak 5%, Wild Trubbish 5%, Wild Garbodor 50%',
	'Black Glasses': ' Desert Resort',
	'Charcoal': ' Castelia City',
	'Deep Sea Scale': ' White Forest, Join Avenue, Wild Chinchou 5%, Wild Lanturn 5%, Wild Gorebyss 5%, Wild Relicanth 5%',
	'Deep Sea Tooth': ' White Forest, Join Avenue, Wild Carvanha 5%, Wild Sharpedo 5%, Wild Huntail 5%, Wild Basculin 5%',
	'Choice Band': ' Gear Station, PWT',
	'Choice Specs': ' Gear Station, PWT',
	'Choice Scarf': ' Gear Station, PWT',
	'Damp Rock': ' Route 8',
	'Draco Plate': ' Undella Bay',
	'Dragon Fang': ' Dragonspiral Tower, Wild Bagon 5%, Wild Shelgon 5%, Wild Salamence 5%, Wild Druddigon 5%',
	'Dread Plate': ' Abyssal Ruins',
	'Earth Plate': ' Abyssal Ruins',
	'Everstone': ' Castelia City, Wild Boldore 50%, Wild Roggenrola 50%, Wild Gigalith 50%, Wild Geodude 5%, Wild Graveler 5%, Wild Golem 5%',
	'Eviolite': ' Castelia City',
	'Expert Belt': ' Driftveil City, Route 19 (Hidden), Wild Throh 1%, Wild Sawk 1%',
	'Fist Plate': ' Abyssal Ruins',
	'Flame Orb': ' Gear Station, PWT, Wild Heatmor 1%',
	'Flame Plate': ' Abyssal Ruins',
	'Focus Sash': ' Gear Station, PWT',
	'Heat Rock': ' Route 8',
	'Icicle Plate': ' Abyssal Ruins',
	'Icy Rock': ' Route 8',
	'Insect Plate': ' Abyssal Ruins',
	'Iron Plate': ' Abyssal Ruins',
	'King\'s Rock': ' Route 13, Wild Poliwhirl 5%, Wild Poliwrath 5%, Wild Slowbro 5%, Wild Politoed 5%, Wild Slowking 5%, Wild Hariyama 5%',
	'Leftovers': ' Castelia Sewers, Wild Snorlax 100%, Wild Munchlax 100%',
	'Life Orb': ' Gear Station, PWT',
	'Light Clay': ' Wild Golett 5%, Wild Golurk 5%',
	'Meadow Plate': ' Abyssal Ruins',
	'Mental Herb': ' Wild Sewaddle 5%, Wild Swadloon 5%, Wild Leavanny 5%',
	'Metal Coat': ' Clay Tunnel, Chargestone Cave, Wild Magnemite 5%, Wild Magneton 5%, Wild Steelix 5%, Wild Beldum 5%, Wild Metang 5%, Wild Metagross 5%, Wild Bronzor 5%, Wild Bronzong 5%, Wild Magnezone 5%',
	'Mind Plate': ' Abyssal Ruins',
	'Miracle Seed': ' Castelia City, Wild Cherubi 5%, Wild Cherrim 5%, Wild Maractus 5%',
	'Mystic Water': ' Route 4, Castelia City, Wild Castform 100%',
	'Never-Melt Ice': ' Dragonspiral Tower (Winter), Wild Snover 5%, Wild Abomasnow 5%, Wild Cryogonal 5%',
	'Poison Barb': ' Route 22, Wild Beedrill 5%, Wild Tentacool 5%, Wild Tentacruel 5%, Wild Qwilfish 5%, Wild Roselia 5%, Wild Budew 5%, Wild Roserade 5%, Wild Vespiquen 5%, Wild Skorupi 5%, Wild Drapion 5%, Wild Venipede 5%, Wild Whirlipede 5%, Wild Scolipede 5%',
	'Quick Claw': ' Skyarrow Bridge, Wild Sandshrew 5%, Wild Sandslash 5%, Wild Meowth 5%, Wild Persian 5%, Wild Sneasel 5%, Wild Zangoose 5%, Wild Weavile 5%',
	'Razor Fang': ' Route 11',
	'Odd Incense': ' Driftveil City',
	'Rock Incense': ' Driftveil City',
	'Wave Incense': ' Driftveil City',
	'Wise Glasses': ' Gear Station, PWT',
	'Sea Incense': ' Driftveil City',
	'Sharp Beak': ' Mistralton City, Wild Fearow 5%, Wild Doduo 5%, Wild Dodrio 5%',
	'Rose Incense': ' Driftveil City',
	'Silver Powder': ' Pinwheel Forest, Wild Butterfree 5%, Wild Masquerain 5%, Wild Wormadam 5%, Wild Mothim 5%, Wild Volcarona 100%',
	'Red Card': ' Gear Station, PWT',
	'Rocky Helmet': ' Relic Passage, PWT',
	'Shell Bell': ' Driftveil City',
	'Silk Scarf': ' Virbank Complex',
	'SilverPowder': ' Wild Butterfree 5%, Wild Masquerain 5%, Wild Wormadam 5%, Wild Mothim 5%, Wild Volcarona 100%',
	'Sky Plate': ' Abyssal Ruins',
	'Smooth Rock': ' Route 8',
	'Stick': ' Route 13, Wild Farfetch\'d 5% ',
	'Soft Sand': ' Desert Resort, Wild Diglett 5%, Wild Dugtrio 5%, Wild Trapinch 5%, Wild Stunfisk 5%',
	'Splash Plate': ' Abyssal Ruins',
	'Spell Tag': ' Celestial Tower, Wild Shuppet 5%, Wild Banette 5%, Wild Yamask 5%, Wild Cofagrigus 5%',
	'Spooky Plate': ' Abyssal Ruins',
	'Stone Plate': ' Abyssal Ruins',
	'Thick Club': ' Wild Cubone 5%, Wild Marowak 5%',
	'Twisted Spoon': ' Castelia Sewers, Wild Abra 5%, Wild Kadabra 5%, Wild Alakazam 5%',
	'Toxic Orb': ' Gear Station, PWT, Wild Muk 1%',
	'Toxic Plate': ' Abyssal Ruins',
	'Zap Plate': ' Abyssal Ruins',
	'Babiri Berry': ' Join Avenue, Wild Snorunt 5%, Wild Glalie 5%, Wild Froslass 5%',
	'Belue Berry': ' Join Avenue',
	'Charti Berry': ' Join Avenue, Wild Taillow 5%, Wild Swellow 5%',
	'Chesto Berry': ' Join Avenue, Wild Whismur 5%, Wild Loudred 5%, Wild Exploud 5%, Wild Spinda 5%, Wild Minccino 50%, Wild Cinccino 50%',
	'Chilan Berry': ' Join Avenue',
	'Chople Berry': ' Join Avenue',
	'Coba Berry': ' Join Avenue',
	'Colbur Berry': ' Join Avenue, Wild Chimecho 5%, Wild Chingling 5%',
	'Durin Berry': ' Join Avenue', 
	'Griseous Orb': ' Dragonspiral Tower',
	'Lustrous Orb': ' Dragonspiral Tower', 
	'Macho Brace': ' Route 16', 
	'Magnet': ' Chargestone Cave', 
	'Muscle Band': ' Gear Station, PWT', 
	'Hard Stone': ' Relic Passage, Join Avenue, Wild Corsola 5%, Wild Nosepass 5%, Wild Aron 5%, Wild Lairon 5%, Wild Aggron 5%, Wild Probopass 5%, Wild Roggenrola 5%, Wild Boldore 5%, Wild Gigalith 5%, Wild Dwebble 5%, Wild Crustle 5%', 
	'Ganlon Berry': ' Join Avenue', 
	'Haban Berry': ' Join Avenue, Wild Gible 5%, Wild Gabite 5%, Wild Garchomp 5%', 
	'Kasib Berry': ' Join Avenue, Wild Duskull 5%, Wild Dusclops 5%, Wild Dusknoir 5%', 
	'Kebia Berry': ' Join Avenue, Wild Shroomish 5%, Wild Breloom 5%', 
	'Leppa Berry': ' Join Avenue, Wild Clefairy 50%, Wild Clefable 50%, Wild Cleffa 50%', 
	'Liechi Berry': ' Join Avenue', 
	'Lum Berry': ' Join Avenue, Wild Mew 100%, Wild Celebi 100%, Wild Shaymin 100%', 
	'Occa Berry': ' Join Avenue, Wild Mawile 5%, Wild Pansage 5%, Wild Simisage 5%', 
	'Metal Powder': ' Route 13, Wild Ditto 5%', 
	'Iron Ball': ' Gear Station, PWT', 
	'Light Ball': ' Wild Pikachu 5%', 
	'Lagging Tail': ' Wild Slowpoke 5%, Wild Lickitung 5%, Wild Lickilicky 5%', 
	'Oran Berry': ' Join Avenue Wild Sentret 5%, Wild Furret 50%, Wild Zigzagoon 5%, Wild Linoone 50%, Wild Bibarel 50%, Wild Pansage 50%, Wild Simisage 50%, Wild Pansear 50%, Wild Simisear 50%, Wild Panpour 50%, Wild Simipour 50%, Wild Audino 50%', 
	'Passho Berry': ' Join Avenue, Wild Phanpy 5%, Wild Donphan 5%, Wild Pansear 5%, Wild Simisear 5%', 
	'Payapa Berry': ' Join Avenue, Wild Mankey 5%, Wild Primeape 5%', 
	'Rawst Berry': ' Join Avenue, Wild Vulpix 100%, Wild Ninetales 100%, Wild Growlithe 50%, Wild Arcanine 50%, Wild Numel 100%, Wild Camerupt 100%, Wild Darumaka 50%, Wild Darmanitan 50%', 
	'Rindo Berry': ' Join Avenue, Wild Finneon 5%, Wild Lumineon 5%, Wild Panpour 5%, Wild Simipour 5%', 
	'Salac Berry': ' Join Avenue', 
	'Shuca Berry': ' Join Avenue, Wild Ponyta 5%, Wild Rapidash 5%', 
	'Sitrus Berry': ' Join Avenue, Wild Furret 5%, Wild Linoone 5%, Wild Bibarel 5%, Wild Audino 5%', 
	'Tanga Berry': ' Join Avenue', 
	'Wacan Berry': ' Join Avenue', 
	'Watmel Berry': ' Join Avenue', 
	'Yache Berry': ' Join Avenue, Wild Starly 5%, Wild Staravia 5%, Wild Staraptor 5%' 
        
    };
    
    var moves = {
    	'Hone Claws':' TM01 Victory Road',
	'Dragon Claw':' TM02 Dragonspiral Tower',
	'Psyshock':' TM03 Giant Chasm',
	'Calm Mind':' TM04 Striaton City Poke Mart',
	'Roar':' TM05 Route 23',
	'Toxic':' TM06 Seaside Cave',
	'Hail':' TM07 Mistralton City Poke Mart',
	'Bulk Up':' TM08 Striaton City Poke Mart',
	'Venoshock':' TM09 Defeat Roxie',
	'Hidden Power':' TM10 Battle Subway, PWT',
	'Sunny Day':' TM11 Mistralton City Poke Mart',
	'Taunt':' TM12 Route 23',
	'Ice Beam':' TM13 Giant Chasm',
	'Blizzard':' TM14 Lacunosa Town Poke Mart',
	'Hyper Beam':' TM15 Route 9 Dept. Store',
	'Light Screen':' TM16 Nimbasa City Poke Mart',
	'Protect':' TM17 Battle Subway, PWT',
	'Rain Dance':' TM18 Mistralton City Poke Mart',
	'Telekinesis':' TM19 Route 18',
	'Safeguard':' TM20 Battle Subway, PWT',
	'Frustration':' TM21 Floccesy Ranch',
	'SolarBeam':' TM22 Pinwheel Forest',
	'Smack Down':' TM23 Battle Subway, PWT',
	'Thunderbolt':' TM24 Victory Road',
	'Thunder':' TM25 Lacunosa Town Poke Mart',
	'Earthquake':' TM26 Route 15',
	'Return':' TM2 Aspertia City',
	'Dig':' TM28 Route 4',
	'Psychic':' TM29 Route 13',
	'Shadow Ball':' TM30 Reversal Mountain',
	'Brick Break':' TM31 Battle Subway, PWT',
	'Double Team':' TM31 Battle Subway, PWT',
	'Reflect':' TM33 Nimbasa City Poke Mart',
	'Sludge Wave':' TM34 Battle Subway, PWT',
	'Flamethrower':' TM35 Route 23',
	'Sludge Bomb':' TM36 Route 8',
	'Sandstorm':' TM37 Mistralton City Poke Mart',
	'Fire Blast':' TM38 Lacunosa Town Poke Mart',
	'Rock Tomb':' TM39 Relic Castle',
	'Aerial Ace':' TM40 Mistralton City',
	'Torment':' TM41 Castelia Sewers',
	'Facade':' TM42 Humilau City',
	'Flame Charge':' TM43 Tubeline Bridge',
	'Rest':' TM44 Castelia City',
	'Attract':' TM45 Castelia City',
	'Thief':' TM46 Virbank Complex',
	'Low Sweep':' TM47 Wellspring Cave',
	'Round':' TM48 Battle Subway, PWT',
	'Echoed Voice':' TM49 Nimbasa City Musical Hall',
	'Overheat':' TM50 N\'s Castle',
	'Ally Switch':' TM51 Battle Subway, PWT',
	'Focus Blast':' TM52 Wellspring Cave',
	'Energy Ball':' TM53 Aspertia City',
	'False Swipe':' TM54 Reversal Mountain',
	'Scald':' TM55 Defeat Marlon',
	'Fling':' TM56 Route 6',
	'Charge Beam':' TM57 Lentimas Town',
	'Sky Drop':' TM58 Mistralton City',
	'Incinerate':' TM59 Battle Subway, PWT',
	'Quash':' TM60 Battle Subway, PWT',
	'Will-O-Wisp':' TM61 Celestial Tower',
	'Acrobatics':' TM62 Defeat Skyla',
	'Embargo':' TM63 Driftveil City Market',
	'Explosion':' TM64 Battle Subway, PWT',
	'Shadow Claw':' TM65 Celestial Tower',
	'Payback':' TM66 Route 16',
	'Retaliate':' TM67 Plasma Frigate',
	'Giga Impact':' TM68 Route 9 Dept. Store',
	'Rock Polish':' TM69 Reversal Mountain',
	'Flash':' TM70 Castelia City',
	'Stone Edge':' TM71 Twist Mountain',
	'Volt Switch':' TM72 Defeat Elesa',
	'Thunder Wave':' TM73 Nimbasa City Poke Mart',
	'Gyro Ball':' TM74 Nimbasa City Poke Mart',
	'Swords Dance':' TM75 Battle Subway, PWT',
	'Struggle Bug':' TM76 Defeat Burgh',
	'Psych Up':' TM77 Battle Subway, PWT',
	'Bulldoze':' TM78 Defeat Clay',
	'Frost Breath':' TM79 Battle Subway, PWT',
	'Rock Slide':' TM80 Mistralton Cave',
	'X-Scissor':' TM81 Route 7',
	'Dragon Tail':' TM82 Defeat Drayden',
	'Work Up':' TM83 Defeat Cheren',
	'Poison Jab':' TM84 Moor of Icirrus',
	'Dream Eater':' TM85 Dreamyard',
	'Grass Knot':' TM86 Pinwheel Forest',
	'Swagger':' TM87 Battle Subway, PWT',
	'Pluck':' TM88 Battle Subway, PWT',
	'U-Turn':' TM89 Battle Subway, PWT',
	'Substitute':' TM90 Twist Mountain',
	'Flash Cannon':' TM91 Twist Mountain',
	'Trick Room':' TM92 Abundant Shrine',
	'Wild Charge':' TM93 Victory Road',
	'Rock Smash':' TM94 Virbank Complex',
	'Snarl':' TM95 Lostlorn Forest',
	'Grass Pledge':' PWT Move Tutor',
	'Fire Pledge':' PWT Move Tutor',
	'Water Pledge':' PWT Move Tutor',
	'Frenzy Plant':' PWT Move Tutor',
	'Blast Burn':' PWT Move Tutor',
	'Hydro Cannon':' PWT Move Tutor',
	'Covet':' Driftveil City Move Tutor',
	'Bug Bite':' Driftveil City Move Tutor',
	'Drill Run':' Driftveil City Move Tutor',
	'Bounce':' Driftveil City Move Tutor',
	'Signal Beam':' Driftveil City Move Tutor',
	'Iron Head':' Driftveil City Move Tutor',
	'Super Fang':' Driftveil City Move Tutor',
	'Uproar':' Driftveil City Move Tutor',
	'Seed Bomb':' Driftveil City Move Tutor',
	'Dual Chop':' Driftveil City Move Tutor',
	'Low Kick':' Driftveil City Move Tutor',
	'Gunk Shot':' Driftveil City Move Tutor',
	'Thunder Punch':' Driftveil City Move Tutor',
	'Fire Punch':' Driftveil City Move Tutor',
	'Ice Punch':' Driftveil City Move Tutor',
	'Last Resort':' Lentimas Town Move Tutor',
	'Iron Defense':' Lentimas Town Move Tutor',
	'Magnet Rise':' Lentimas Town Move Tutor',
	'Magic Coat':' Lentimas Town Move Tutor',
	'Block':' Lentimas Town Move Tutor',
	'Hyper Voice':' Lentimas Town Move Tutor',
	'Electroweb':' Lentimas Town Move Tutor',
	'Icy Wind':' Lentimas Town Move Tutor',
	'Iron Tail':' Lentimas Town Move Tutor',
	'Aqua Tail':' Lentimas Town Move Tutor',
	'Earth Power':' Lentimas Town Move Tutor',
	'Zen Headbutt':' Lentimas Town Move Tutor',
	'Foul Play':' Lentimas Town Move Tutor',
	'Superpower':' Lentimas Town Move Tutor',
	'Gravity':' Lentimas Town Move Tutor',
	'Dragon Pulse':' Lentimas Town Move Tutor',
	'Dark Pulse':' Lentimas Town Move Tutor',
	'Draco Meteor':' Opelucid City Move Tutor',
	'Bind':' Humilau City Move Tutor',
	'Snore':' Humilau City Move Tutor',
	'Heal Bell':' Humilau City Move Tutor',
	'Knock Off':' Humilau City Move Tutor',
	'Synthesis':' Humilau City Move Tutor',
	'Roost':' Humilau City Move Tutor',
	'Sky Attack':' Humilau City Move Tutor',
	'Role Play':' Humilau City Move Tutor',
	'Heat Wave':' Humilau City Move Tutor',
	'Giga Drain':' Humilau City Move Tutor',
	'Drain Punch':' Humilau City Move Tutor',
	'Pain Split':' Humilau City Move Tutor',
	'Tailwind':' Humilau City Move Tutor',
	'Worry Seed':' Nacrene City Move Tutor',
	'Gastro Acid':' Nacrene City Move Tutor',
	'Helping Hand':' Nacrene City Move Tutor',
	'After You':' Nacrene City Move Tutor',
	'Magic Room':' Nacrene City Move Tutor',
	'Wonder Room':' Nacrene City Move Tutor',
	'Spite':' Nacrene City Move Tutor',
	'Recycle':' Nacrene City Move Tutor',
	'Trick':' Nacrene City Move Tutor',
	'Stealth Rock':' Nacrene City Move Tutor',
	'Outrage':' Nacrene City Move Tutor',
	'Endeavor':' Nacrene City Move Tutor',
	'Sleep Talk':' Nacrene City Move Tutor',
	'Skill Swap':' Nacrene City Move Tutor',
	'Snatch':' Nacrene City Move Tutor'
    };
    
    var locations = {
    	'Snivy':' Starter',
	'Servine':' Evolve Snivy',
	'Bulbasaur':' RGB- Starter; Yellow- Cerulean City; GS- Trade; Crystal-  Trade; RS- Trade; FR/LG- Starter; Emerald- Trade; DP- Trade; Pt- Trade; HGSS- Defeat Red; BW- Transfer; BW2- Transfer; XY- Lumiose City; ORAS- Trade',
	'Ivysaur':' All games- Evolve Bulbasaur, XY- Friend Safari Grass',
	'Venusaur':' All games- Evolve Ivysaur',
	'Charmander':' RGB- Starter; Yellow- Route 24; GS- Trade; Crystal-  Trade; RS- Trade; FR/LG- Starter; Emerald- Trade; DP- Trade; Pt- Trade; HGSS- Defeat Red; BW- Transfer; BW2- Transfer; XY- Lumiose City; ORAS- Trade',
	'Charmeleon':' All games- Evolve Charmander, XY- Friend Safari Fire',
	'Charizard':' All games- Evolve Charmeleon',
	'Squirtle':' RGB- Starter; Yellow- Vermillion City; GS- Trade; Crystal-  Trade; RS- Trade; FR/LG- Starter; Emerald- Trade; DP- Trade; Pt- Trade; HGSS- Defeat Red; BW- Transfer; BW2- Transfer; XY- Lumiose City; ORAS- Trade',
	'Wartortle':' All games- Evolve Squirtle, XY- Friend Safari Water',
	'Blastoise':' All games- Evolve Wartortle',
	'Serperior':' Evolve Servine',
	'Rattata':' RB- Routes 1, 2, 4, 9, 16, 21, and 22; Yellow- Routes 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 16, 18, 21, and 22, Pokémon Mansion; Gold- Routes 1, 3, 4, 7, 9, 11, 22, 29, 30, 31, 32, 33, 34, 38, 39, and 46, Bell Tower, Mt. Mortar, Union Cave, Tohjo Falls, Sprout Tower and Burned Tower; Silver- Routes 1, 3, 4, 7, 9, 11, 22, 29, 30, 31, 32, 33, 34, and 46, Bell Tower, Mt. Mortar,Union Cave, Tohjo Falls, Sprout Tower and Burned Tower; Crystal- Routes 1, 3, 4, 7, 9, 11, 21, 22, 29, 32, 33, 34, 38, 39, 42 and 46, Bell Tower, Mt. Mortar, Union Cave, Tohjo Falls, Sprout Tower and Burned Tower; RSE/XY- Trade; FRLG- Routes 1, 2, 4, 9, 16, 17, 18, and 22, Pokémon Mansion; DPPt- Routes 225 and 226; HG- Routes 1, 3, 4, 7, 9, 11, 22, 29, 30, 31, 32, 33, 34, 38, 39, and 46, Sprout Tower,Union Cave, Burned Tower, Bell Tower, Mt. Mortar; SS- Routes 1, 3, 4, 7, 9, 11, 22, 29, 30, 31, 32, 33, 34 and 46, Sprout Tower, Union Cave,Burned Tower, Bell Tower, Mt. Mortar; BW- Breed; BW2- Castelia City, Castelia Sewers, Relic Passage; ORAS- Route 117 (hidden Pokémon)',
	'Raticate':' RB- Routes 16, 17, 18, and 21; Yellow- Routes 9, 10, 11, 16, 18, and 21, Pokémon Mansion; GS- Routes 7, 9, 10, 26, 27, 38, and 39, Union Cave, Burned Tower; Crystal- Routes 1, 3, 4, 6, 7, 9, 10, 11, 21, 26, 27, 38, 39, 42, and 43, Mt. Mortar, Union Cave,Tohjo Falls, Burned Tower; RSE/XY- Trade; FRLG- Routes 16, 17, and 18, Pokémon Mansion; DPPt- Routes 225 and 226; HGSS- Routes 7, 9, 10, 26, 27, 38, 39, and 47, Mt. Mortar, Union Cave, Burned Tower, Tohjo Falls, Safari Zone; BW- Dreamyard; BW2- Dreamyard, Strange House, and Relic Passage; ORAS- Route 118 (hidden Pokémon)',
	'Spearow':' RB- Routes 3, 4, 9, 10, 11, 16, 17, 18, 22, and 23; Yellow- Routes 3, 4, 9, 16, 18, and 22; GSC- Routes 3, 4, 7, 9, 10, 22, 33, 42, and 46, Headbutt trees, Received from Randy; RSE/ORAS- Trade; FRLG- Routes 3, 4, 9, 10, 11, 16, 17, 18, 22, and 23, Treasure Beach, Mt. Ember, Cape Brink, Ruin Valley, Water Path, Canyon Entrance; DP- Routes 225 and 226; Pt- Route 225; HGGS- Routes 3, 4, 7, 9, 10, 22, 33, 42, 46, and 47, Safari Zone, Headbutt trees, Received from Webster; BW/BW2- Breed; XY- Friend Safari (Flying)',
	'Fearow':' RB- Routes 17, 18, and 23; Yellow- Routes 9, 16, 17, 18, and 23; GS- Routes 9, 10, 16, 17, 18, and 22; Crystal- Routes 9, 10, 16, 17, 18, 22, and 42; RSE/ORAS- Trade; FRLG- Routes 17, 18, and 23, Treasure Beach, Kindle Road, Mt. Ember, Cape Brink, Ruin Valley, Water Path, Canyon Entrance, Sevault Canyon; DPPt- Routes 225, 226, and 227, Stark Mountain; HGSS- Routes 9, 10, 16, 17, 18, 22, 47, and 48, Safari Zone; BW/BW2- Route 15; XY- Victory Road (flying shadow)',
	'Ekans':' Red- Routes 4, 8, 9, 10, 11, and 23; BY/RSE/LG/ORAS- Trade; Gold- Goldenrod Game Corner; Silver- Routes 3, 4, 32, and 33; Crystal- Routes 3, 4, 32, 33, and 42, Headbutting trees; FR- Routes 4, 8, 9, 10, 11 and 23; DPPt- Route 212; HG- Goldenrod Game Corner, Safari Zone; SS- Routes 3, 4, 32 33, and Safari Zone; BW/BW2- Poke Transfer; XY- Route 14 Horde',
	'Arbok':' Red- Route 23 and Cerulean Cave; BY/RSE/LG/ORAS- Trade; Gold- Evolve Ekans; Silver- Routes 3, 4, 26, and 27; Crystal- Routes 3, 4, 26, 27, 28, and 42, Mt. Silver; FR- Route 23 and Victory Road; DPPt- Great Marsh; HG- Safari Zone; SS- Routes 3, 4, 26, and 27, Safari Zone; BW/BW2- Poke Transfer; XY- Route 19 Horde',
	'Caterpie':' Red- Route 25, Viridian Forest; Blue- Routes 2, 24, 25, Viridian Forest; Blue (Japan)- Routes 4, 8, 9, 10, 11, and 23; Yellow- Viridian Forest; Gold/HG- Routes 2, 30, and 31, Ilex Forest, National Park, Headbutt trees, Bug-Catching Contest; Silver/SS- Bug-Catching Contest; Crystal- Routes 2, 24, 25, 30, and 31, Ilex Forest, National Park, Bug-Catching Contest; RSE- Trade; FR/LG- Routes 2, 24, and 25, Viridian Forest, Pattern Bush; DP- Route 204; Pt- Route 204, Eterna Forest; BW- Trade or breed; BW2- Trade or breed; X- Santalune Forest; Y- Route 2, Santalune Forest; ORAS- Trade',
	'Metapod':' Red- Route 25, Viridian Forest; Blue- Routes 24 and 25, Viridian Forest; Yellow- Viridian Forest; Gold/HG- Routes 2, 30, and 31, Ilex Forest, National Park, Headbutt trees, Bug-Catching Contest; Silver/SS- Bug-Catching Contest; Crystal- Routes 24 and 25, Ilex Forest, Bug-Catching Contest; RSE- Trade; FR/LG- Routes 24 and 25, Viridian Forest, Pattern Bush; DPPt- Eterna Forest; B/B2- Trade; W- Route 12; W2- Evolve Caterpie;  X- Evolve Caterpie; Y- Santalune Forest; ORAS- Trade',
	'Butterfree':' RBY/FR/LG/DPPt: Evolve Metapod; Gold/HG- Route 2, Viridian Forest, Headbutt trees, Bug-Catching Contest; Silver/SS- Bug-Catching Contest; Crystal- Routes 2, 24, and 25, Bug-Catching Contest, Headbutt trees; RSE- Trade;  B/B2- Trade; W- Route 12 (Shaking Grass); W2- Pinwheel Forest (Hidden Grotto);  XY- Friend Safari (Bug); ORAS- Trade',
	'Tepig':' Starter',
	'Pignite':' Evolve Tepig',
	'Emboar':' Evolve Pignite',
	'Oshawott':' Starter',
	'Dewott':' Evolve Oshawott',
	'Samurott':' Evovle Dewott',
	'Lillipup':' Floccesy Ranch Grass 40%',
	'Patrat':' Route 19 Grass 50%, Route 19 Shaking Grass 100%, Virbank Complex Outside Grass 35%',
	'Watchog':' Route 1 Grass & Dark Grass 40%, Route 2 Grass 30%',
	'Purrloin':' Route 19 Grass 50%',
	'Liepard':' Dreamyard Grass & Dark Grass 25%, Route 2 Grass 20%, Route 5 Grass & Dark Grass 20%',
	'Pidove':' Virbank Complex Outside Grass 35%, Route 20 Autumn, Spring, Winter Grass & Dark Grass 25%',
	'Tranquill':' Victory Road Outside Grass & Dark Grass 80%, Dragonspiral Tower Grass 35 %, Routes 3 & 7 Grass & Dark Grass 30%',
	'Unfezant':' Routes 3, 6, 7, & 12 Shaking Grass 5%,  Dragonspiral Tower Shaking Grass 5%',
	'Sewaddle':' Route 20 Grass 35%',
	'Swadloon':' Pinwheel & Lostlorn Forest Grass & Dark Grass 25%',
	'Leavanny':' Routes 6 & 12 Shaking Grass 5%, Lostlorn Forest Shaking Grass 5%',
	'Sunkern':' Route 20 Summer Grass & Dark Grass 26%',
	'Sunflora':' Evolve Sunkern',
	'Nidorino':' R/FR- Safari Zone; Blue- Safari Zone, Celadon Game Corner; Yellow- Routes 9 and 23, Safari Zone; GSC- Routes 13, 14, and 15; RSE/Black/ORAS- Trade; LG- Safari Zone, Trade Nidorina on Route 11; DPPt- Route 221, Valor Lakefront; HGSS- Route 15, Safari Zone; W/BW2- Evolve Nidoran-M; XY- Route 11',
	'Nidoking':' RBY/GSC/FRLG/DPPt/HGSS/W/BW2/XY- Evolve Nidorino; RSE/Black/ORAS- Trade',
	'Celfairy':' RB/FRLG- Mt. Moon, Rocket Game Corner; Yellow- Mt. Moon; GS- Mt. Moon; Crystal- Mt. Moon, Routes 3 and 4; RSE- Trade; DPPt- Mt. Coronet; HGSS- Mt. Moon, Safari Zone; BW/BW2- Giant Chasm; XY- Friend Safari (Fairy); ORAS- Route 115, Meteor Falls',
	'Clefable':' RBY/GSC/FRLG/DPPt/HGSS/XY/ORAS- Evolve Clefairy; RSE- Trade; BW/BW2- Giant Chasm (Shaking Grass)',
	'Vulpix':' Red/Gold/Crystal/HG- Trade; Blue/LG- Routes 7 and 8, Pokémon Mansion; Yellow- Rocket Game Corner; Silver- Routes 7, 8, 36, and 37; RSE- Mt. Pyre exterior; DP- Route 209; Pt- Routes 209 and 214; SS- Routes 7, 8, 36, 37, and 48; BW/BW2- Abundant Shrine; XY- Breed Ninetales; ORAS- Mt. Pyre exterior, Mirage Forest',
	'Ninetales':' Red/Gold/Crystal/FR/HG- Trade; Blue/Yellow/Silver/RSE/LG/DPPt/SS/ORAS- Evolve Vulpix; BW/BW2- Abundant Shrine (Shaking Grass); XY- Friend Safari (Fire)',
	'Jigglypuff':' RB/FRLG- Route 3; Yellow: Routes 5, 6, 7, and 8; GS- Routes 3, 4, and 46; Crystal- Routes 5, 6, 7, 8, 34, and 35; RSE- Route 115; DPPt- Trophy Garden; HGSS- Routes 3 and 4, Safari Zone; BW- Route 14; BW2- Routes 1 and 2, Dreamyard; XY- Route 20, Pokémon Village, Friend Safari (Fairy); ORAS- Route 115',
	'Wigglytuff':' RB- Cerulean Cave; Yellow- Rocket Game Corner; GSC/RSE/FRLG/DPPt/HGSS/XY/ORAS- Evolve Jigglypuff; BW- Route 14; BW2- Routes 1 and 2, Dreamyard',
	'Zubat':' RBY- Mt. Moon, Rock Tunnel, Seafoam Islands, andVictory Road; GS- Rock Tunnel, Whirl Islands, Ilex Forest, Mt. Moon,Dark Cave, Ice Path, Mt. Mortar, Union Cave,Tohjo Falls, Burned Tower, and Slowpoke Well, Routes 3, 4, 32, 33, and 42; Crystal- Rock Tunnel, Whirl Islands, Ilex Forest, Mt. Moon,Dark Cave, Ice Path, Mt. Mortar, Union Cave,Tohjo Falls, Burned Tower, and Slowpoke Well, Routes 3, 4, 9, 10, 30, 31, 32, 33, and 42; RS- Cave of Origin, Granite Cave, and Victory Road, Meteor Falls, Seafloor Cavern, and Shoal Cave; Emerald- Altering Cave, Cave of Origin, Granite Cave, andVictory Road, Meteor Falls, Seafloor Cavern, and Shoal Cave; FRLG- Mt. Moon, Rock Tunnel, Seafoam Islands, Victory Road, Icefall Cave, and Lost Cave; DP- Iron Island, Oreburgh Mine, Wayward Cave, and Lost Tower, Routes 203, 204, 206, 207, 208, 209, 211, 216, and 217, Acuity Lakefront, Ravaged Path, Oreburgh Gate, and Mt. Coronet; Pt- Iron Island, Oreburgh Mine, Wayward Cave, Lost Tower, Routes 203, 204, 206, 207, 208, 209, 211, 214, and 216, Acuity Lakefront, Ravaged Path, Oreburgh Gate, Mt. Coronet; HGSS- Dark Cave, Union Cave, the Slowpoke Well, Ilex Forest, Burned Tower, Mt. Mortar, Ice Path, and Whirl Islands, Routes 3, 32, and 33, Cliff Cave, Safari Zone; BW- Breed; BW2- Castelia Sewers; XY- Connecting Cave; ORAS- Granite Cave, Meteor Falls, Sealed Chamber, Scorched Slab, Cave of Origin, Seafloor Cavern, Shoal Cave,Victory Road',
	'Golbat':' RBY- Seafoam Islands, Victory Road, and Cerulean Cave; GS- Dark Cave, Union Cave, Slowpoke Well, Mt. Mortar, Whirl Islands, Ice Path, Mt. Silver, Victory Road, and Tohjo Falls; Crystal- Dark Cave, Union Cave, Slowpoke Well, Mt. Mortar, Whirl Islands, Ice Path, Mt. Silver*, Victory Road, Rock Tunnel, and Tohjo Falls, Routes 28 and 42, Mt. Silver; RSE- Cave of Origin, Shoal Cave, and Sky Pillar, Meteor Falls, Seafloor Cavern, and Victory Road; FRLG- Cerulean Cave, Icefall Cave, Lost Cave, Seafoam Islands, and Victory Road; DP- Ravaged Path, Oreburgh Gate, Victory Road, and Mt. Coronet, Stark Mountain, Mt. Coronet, Victory Road, Iron Island, Snowpoint Temple, Lost Tower, and Turnback Cave, Route 227; Pt- Ravaged Path, Oreburgh Gate, Victory Road, and Mt. Coronet, Stark Mountain, Oreburgh Gate, Mt. Coronet, Victory Road, Iron Island, Snowpoint Temple, Lost Tower, and Turnback Cave, Route 227; HGSS- Cliff Cave, Dark Cave, Ice Path, Mt. Mortar, Mt. Silver, Slowpoke Well, Union Cave, Cerulean Cave, Seafoam Islands, and Victory Road, Safari Zone; BW- Route 13, Giant Chasm; BW2- Dreamyard, Celestial Tower, and Strange House; XY- Evolve Zubat; ORAS- Meteor Falls, Cave of Origin, Seafloor Cavern,Shoal Cave, Scorched Slab, Victory Road, Sky Pillar, Sealed Chamber',
	'Oddish':' Red- Routes 5, 6, 7, 12, 13, 14, 15, 24, and 25; Blue/LG/Black/BW2- Trade; Yellow- Routes 12, 13, 14, 15, 24, and 25; GS- Routes 5, 6, 24, and 25, Ilex Forest; Crystal- Routes 24 and 25, Ilex Forest; RSE- Routes 110, 117, 119, 120, 121, and 123, Safari Zone; FR- Routes 5, 6, 7, 12, 13, 14, 15, 24, and 25, Berry Forest, Bond Bridge, Cape Brink, Water Path; DP- Routes 229 and 230; Pt- Routes 224 and 230; HGSS- Routes 5, 6, 24, and 25, Ilex Forest, Safari Zone; White- White Forest; XY- Route 6, Friend Safari (Grass); ORAS- Routes 110 and 117, Routes 119, 120, and Safari Zone',
	'Herdier':' Route 1 Dark Grass 39%, Route 1 Grass 50%',
	'Stoutland':' Route 1, 2, 3 Shaking Grass 5%, P2 Laboratory Shaking Grass 5%',
	'Mareep':' Floccesy Ranch Grass 10%',
	'Flaaffy':' Evolve Mareep',
	'Gloom':' Red- Routes 12, 13, 14, and 15; Blue/LG/Black/BW2- Trade; Yellow- Routes 12, 13, 14, and 15, Cerulean Cave; GS- Route 5; Crystal- Route 24; RSE- Routes 121 and 123, Safari Zone; FR- Routes 12, 13, 14, and 15, Berry Forest, Bond Bridge, Cape Brink, Water Path; DP- Routes 224, 229, and 230; Pt- Routes 224 and 230; HGSS- Routes 5, 47, and 48; White- Evolve Oddish; XY- Friend Safari (Poison); ORAS- Routes 119, 120, 121, and 123, Safari Zone', 
	'Vileplume':' Red/Yellow/GSC/RSE/FR/DPPt/HGSS/White/XY/ORAS- Evolve Gloom; Blue/LG/Black/BW2- Trade',
	'Paras':' RBY/FRLG- Mt. Moon, Safari Zone; GSC- National Park (Bug-Catching Contest), Ilex Forest, Mt. Moon; RSE/Black/BW2- Trade; DPPt- Great Marsh; HGSS- National Park (Bug-Catching Contest), Ilex Forest, Mt. Moon, Safari Zone; White- Route 11; XY- Friend Safari (Bug); ORAS- Petalburg Woods (hidden Pokémon*)',
	'Parasect':' RB/FRLG/HGSS- Safari Zone, Cerulean Cave; Yellow- Safari Zone, Cerulean Cave, Trade for Tangela on Route 18; GS/DPPt/White/XY/ORAS- Evolve Paras; Crystal- Mt. Silver Cave; RSE/Black/BW2- Trade',
	'Venonat':' RB- Routes 12, 13, 14, and 15, Safari Zone; Yellow- Routes 14, 15, 24, and 25; GS- Routes 24, 25, and 43, Bug-Catching Contest; Crystal- Routes 9, 10, 14, 15, 24, 25, and 43, Ilex Forest,National Park, Bug-Catching Contest; RSE- Trade; FRLG- Routes 12, 13, 14, and 15, Berry Forest, Bond Bridge, Safari Zone; DPPt- Route 229; HGSS- Routes 24, 25, 43, Bug-Catching Contest, Route 43, Lake of Rage (Headbutt trees); BW/XY/ORAS- Breed; BW2- Route 3 (Hidden Grotto)',
	'Venomoth':' RB- Safari Zone, Victory Road, Cerulean Cave; Yellow- Routes 14 and 15, Cerulean Cave; GS/HGSS- Routes 24 and 25; Crystal- Routes 9, 10, 13, 14, 15, 24, 25, and 43; RSE- Trade; FRLG- Safari Zone, Berry Forest; DPPt- Route 229; BW- Dreamyard; BW2- Evolve Venonat; XY- Friend Safari (Bug and Poison); ORAS- Mirage Islands (west of Route 104, west ofDewford Town, north of Route 124, south of Route 134)',
	'Diglett':' RBY/GSC/FRLG- Diglett Cave; RSE- Trade; DPPt- Route 228; HGSS- Diglett Cave, Route 48; BW/BW2- Poke Transfer; XY- Breed Dugtrio; ORAS- Fiery Path (Hidden Pokemon)',
	'Dugtrio':' RB/GSC/FRLG/HGSS- Diglett Cave; Yellow- Digglet Cave, Trade Lickitung on Route 11; RSE- Trade; DPPt- Route 228; BW/BW2- Poke Transfer; XY- Route 13, Friend Safari (Ground); ORAS- Evolve Diglett',
	'Meowth':' RY/Gold/RS/HG/BW/XY- Trade; Blue- Routes 5, 6, 7, and 8; Silver- Routes 5, 6, 7, 8, 38, and 39; Crystal- Routes 5, 6, 7, 8, 11, 38, and 39; Emerald- Trade Skitty in Battle Frontier; FRLG- Routes 5, 6, 7, and 8, Bond Bridge, Canyon Entrance, Cape Brink, Five Isle Meadow, Kindle Road, Ruin Valley, Sevault Canyon, Treasure Beach, Water Path; DPPt- Trophy Garden; SS- Routes 5, 6, 7, 8, 38, and 39; BW2- Trade with Yancy in Nimbasa City (male player character only); ORAS- Breed Persian', 
	'Persian':' RY/Gold/RS/HG/BW/XY- Trade; Blue/Emerald/DPPt/BW2- Evolve Meowth; Silver/Crystal- Route 7; FRLG- Bond Bridge, Canyon Entrance, Cape Brink, Five Isle Meadow, Kindle Road, Ruin Valley, Sevault Canyon, Treasure Beach, Water Path; SS- Route 7, Cerulean Cave; ORAS- Mirage Island (North of Route 124)', 
	'Psyduck':' RB- Seafoam Islands, Routes 4*, 24, and 25, Cerulean City, Cerulean Gym, Safari Zone (Super Rod); Yellow- Route 6 (Surfing); GS- Routes 6 and 35, Ilex Forest (Surfing); Crystal- Routes 6 and 35, Ilex Forest (Surfing), Routes 6 and 35, Ilex Forest, National Park (tall grass); RSE- Safari Zone; FR- Celadon City (Surfing), Routes 4, 10, 11, 12, 13, 19, 20, 21, and 24,Water Labyrinth, Resort Gorgeous, Memorial Pillar, Green Path, Outcast Island, Tanoby Ruins,Pallet Town, Cerulean City, Vermilion City,Cinnabar Island, One Island, Five Island, Trainer Tower (Super Rod), Routes 6, 22, 23, and 25, Viridian City, Fuchsia City, Four Island, Cerulean Cave, Safari Zone(Surfing and Super Rod), Treasure Beach, Kindle Road, Bond Bridge, Five Isle Meadow, Ruin Valley, Water Path (tall grass and Super Rod), Cape Brink, Berry Forest (tall grass, surfing, and Super Rod), Seafoam Islands, Icefall Cave (walking, surfing, and Super Rod), Canyon Entrance (tall grass); LG- Trade; DP- Routes 204, 208, 209, 210, 212, and 214, Twinleaf Town, Eterna City, Lake Verity (Surfing), Routes 208 and 210, Lake Acuity, Lake Valor,Great Marsh (tall grass), Oreburgh Gate, Ravaged Path (walking and surfing); Pt- Routes 204, 208, 209, 210, 212, 214, and 225,Twinleaf Town, Eterna City, Lake Verity, Resort Area (Surfing), Routes 208 and 210, Lake Acuity, Lake Valor,Great Marsh (tall grass), Oreburgh Gate, Ravaged Path (walking and surfing); HGSS- Routes 6 and 35, Ilex Forest, Seafoam Islands,Cerulean Cave, Safari Zone; BW- Breed; BW2- Floccesy Ranch; XY- Routes 7 and 22; ORAS- Safari Zone (walking and surfing)',
	'Golduck':' RB- Seafoam Islands (walking); Yellow- Route 6 (surfing); GS- Routes 6 and 35, Ilex Forest (surfing), Mt. Silver* (walking); Crystal- Mt. Silver* (walking), Routes 6 and 35, Ilex Forest, Mt. Silver* (surfing); RSE- Safari Zone; FR- Cerulean Cave and Berry Forest (Surfing), Seafoam Islands and Cape Brink (Tall grass/walking and surfing); LG- Trade; DP- Routes 203, 204, 205, 208, 209, 210, 212, 214and 225, Twinleaf Town, Eterna City, Celestic Town, Ravaged Path, Oreburgh Gate, LakesVerity, Acuity, and Valor, Sendoff Spring, Resort Area (surfing), Routes 226, and 230, Great Marsh, Sendoff Spring (tall grass/walking); Pt- Routes 203, 204, 205, 208, 209, 210, 212, 214and 225, Twinleaf Town, Eterna City, Celestic Town, Ravaged Path, Oreburgh Gate, LakesVerity, Acuity, and Valor, Sendoff Spring, Resort Area (surfing), Route 226, Oreburgh Gate, Lakes Acuity, andValor (tall grass/walking); HGSS- Routes 6 and 35, Ilex Forest (surfing), Mt. Silver,Seafoam Islands; BW- Routes 11 and 14, Village Bridge; BW2- Routes 11, 14, 22 and 23, Village Bridge, Seaside Cave, Abundant Shrine and Nature Preserve, Route 23 and Abundant Shrine* (Hidden Grotto); XY/ORAS- Evolve Psyduck',
	'Ampharos':' Evolve Flaaffy',
	'Weedle':' Red- Routes 2, 24, and 25, Viridian Forest; Blue- Route 25, Viridian Forest; Yellow- Trade; G/HG- Bug-Catching Contest; S/SS- Routes 2, 30, and 31, Ilex Forest, Bug-Catching Contest, Headbutt trees; Crystal- Routes 30 and 31, Ilex Forest, National Park, Bug-Catching Contest; RSE- Trade; FRLG- Routes 2, 24, and 25, Viridian Forest, Pattern Bush; DPPt- Route 204, Eterna Forest; BB2- Breed; WW2- Trade; X- Route 2, Santalune Forest; Y- Santalune Forest; ORAS- Breed',
	'Kakuna':' Red- Routes 24 and 25, Viridian Forest; Blue- Route 25, Viridian Forest; Yellow- Trade; G/HG- National Park (Bug-Catching Contest); S/SS- Routes 2, 30, and 31, Ilex Forest, Viridian Forest, National Park (Bug-Catching Contest), Headbutt trees; DPPt- Eterna Forest; Black- Route 12; B2- Evolve Weedle; W/W2- Trade; X- Santalune Forest, Friend Safari (Poison); Y- Friend Safari (Poison), ORAS- Safari Zone (hidden Pokémon)',
	'Beedrill':' RB/FRLG/DPPt/XY/ORAS- Evolve Kakuna; Yellow/RSE/WW2- Trade; G/HG- Bug-Catching Contest; S/SS- Route 2, Bug-Catching Contest, Headbutt trees; Black- Route 12 (Shaking Grass); B2- Pinwheel Forest (Hidden Grotto)',
	'Pidgey':' RB- Routes 1, 2, 3, 5, 6, 7, 8, 12, 13, 14, 15, 21, 24, and 25; Yellow- Routes 1, 2, 5, 6, 7, 8, 11, 12, 13, 21, 24, and 25, Viridian Forest; GS- Routes 1, 2, 5, 25, 29, 30, 31, 32, 34, 35, 36, and 37, National Park; Crystal- Routes 1, 2, 5, 25, 29, 30, 31, 35, 36, and 37, National Park, Ilex Forest; RSE/BB2/W2- Trade; FRLG- Routes 1, 2, 3, 5, 6, 7, 8, 12, 13, 14, 15, 24, and 25, Bond Bridge, Berry Forest, Five Isle Meadow; DPPt- Route 229; HGSS- Routes 1, 2, 5, 6, 25, 29, 30, 31, 35, 36, and 37, National Park, Viridian Forest; White- White Forest; XY- Routes 2 and 3, Friend Safari (Flying); ORAS- Breed',
	'Pidgeotto':' RB- Routes 14, 15, and 21; Yellow- Routes 5, 6, 7, 8, 11, 12, 13, 14, 15, 21, 24, and 25, Viridian Forest; GS- Routes 2, 8, 13, 14, 15, 25, 37, and 43; Crystal- Routes 2, 5, 8, 11, 13, 14, 15, 25, 37, 38, 39, and 43; RSE/BB2W2- Trade; FRLG- Routes 13, 14, and 15, Bond Bridge, Berry Forest, Five Isle Meadow; DPPt/White/XY- Evolve Pidgey; HGGS- Routes 2, 8, 13, 14, 15, 25, 37, and 43, Viridian Forest; ORAS- Safari Zone (hidden Pokémon*)',
	'Pidgeot':' All Games- Evolve Pidgeotto',
	'Azurill':' Route 20 Surf 30%, Flocessy Ranch Surf 30%',
	'Marill':' Routes 6 & 22, Abundant Shrine, Pinwheel Forest, Relic Passage, & Victory Road Surf Rippling Water 60%,',
	'Azumarill':' Routes 6, 11, 20, and 22 Surf Rippling Water 5%',
	'Riolu':' Floccesy Ranch Grass 5%',
	'Lucario':' Evolve Riolu',
	'Dunsparce':' Routes 1, 2, 6, 12, 18, & 20 Shaking Grass 10%',
	'Audino':' Any Shaking Grass',
	'Pansage':' Pinwheel & Lostlorn Forest Shaking Grass 10%',
	'Simisage':' Evolve Pansage',
	'Pansear':' Pinwheel & Lostlorn Forest Shaking Grass 10%',
	'Simisear':' Evolve Pansear',
	'Panpour':' Pinwheel & Lostlorn Forest Shaking Grass 10%',
	'Simipour':' Evolve Pansear',
	'Venipede':' Route 20 Dark Grass 20%, Lostlorn Forest Grass 20%',
	'Whirlipede':' Lostlorn Forest Dark Grass 20%',
	'Scolipede':' Pinwheel Forest Shaking Grass 5%',
	'Koffing':' Virbank Complex Grass & Dark Grass 15%',
	'Weezing':' P2 Laboratory Grass 15%',
	'Magnemite':' Virbank Complex Grass & Dark Grass 25%',
	'Magneton':' P2 Laboratory Grass 15%',
	'Magnezone':' P2 Laboratory Shaking Grass 5%',
	'Growlithe':' Virbank Complex Grass & Dark Grass 20%',
	'Arcanine':' Evolve Growlithe',
	'Magby':' Virbank Complex Grass & Dark Grass 25%',
	'Magmar':' Evolve Magby',
	'Magmortar':' Evolve Magmar',
	'Elekid':' Trade Required',
	'Electabuzz':' Trade Required',
	'Electivire':' Trade Required',
	'Crobat':' Dreamyard Shaking Grass 5%',
	'Grimer':' Castelia Sewers Surf & Fishing 100%',
	'Muk':' Castelia Sewers Fish Rippling Water 10%',
	'Woobat':' Wellspring Cave 1F & B1F Grass 50%',
	'Swoobat':' Evolve Woobat',
	'Roggenrola':' Relic Passage Room 3 34%',
	'Boldore':' Giant Chasm Outside Grass 100%, Victory Road 2F & 4F Grass 80%',
	'Gigalith':' Evolve Boldore',
	'Onix':' Twist Mountain, Relic Passage, Clay Tunnel, Underground Ruins, & Victory Road Dust Clouds 20%',
	'Steelix':' Twist Mountain Dusk Clouds 5%',
	'Timburr':' Relic Passage Room 3 Grass 20%',
	'Gurdurr':' Victory Road Cliffside Grass & Dark Grass 70%',
	'Conkeldurr':' Evolve Gurdurr',
	'Drilbur':' Mistralton & Chargestone Cave Dust Clouds 100%',
	'Excadrill':' Giant Chasm Cave, Reversal Mountain, Seaside Cave, & Wellspring Cave Dust Clouds 100%',
	'Skitty':' Trade Required',
	'Delcatty':' Trade Required',
	'Buneary':' Castelia City Park Grass & Dark Grass 15%',
	'Lopunny':' Castelia City Park Shaking Grass 5%',
	'Cottonee':' Victory Road Forest Grass & Dark Grass 70%',
	'Whimsicott':' Pinwheel, Lostlorn, & Victory Road Forest Shaking Grass 5%',
	'Petilil':' Trade Required',
	'Lilligant':' Trade Required',
	'Munna':' Dreamyard Grass & Dark Grass 20%',
	'Musharna':' Dreamyard Shaking Grass 5%',
	'Cleffa':' Breed Clefairy',
	'Eevee':' Castelia City Park Grass & Dark Grass 5%',
	'Vaporeon':' Evolve Eevee',
	'Jolteon':' Evolve Eevee',
	'Flareon':' Evolve Eevee',
	'Espeon':' Evolve Eevee',
	'Umbreon':' Evolve Eevee',
	'Leafeon':' Evolve Eevee',
	'Pikachu':' RB/FRLG- Viridian Forest, Power Plant; Yellow- Starter; GS- Route 2; Crystal- Route 2, Celadon Game Corner; RSE/ORAS- Safari Zone; DPPt- Trophy Garden; BW/BW2- Poke Transfer; XY- Santalune Forest, Route 3, Friend Safari (Electric)', 
	'Raichu':' Red- Cerulean Cave; Blue- Power Plant, Cerulean Cave; Yellow- Trade; GSC/RSE/FRLG/DPPt/HGSS/XY/ORAS- Evolve Pikachu; BW/BW2- Poke Transfer',
	'Sandshrew':' Red/FR- Trade; Blue- Routes 4, 8, 9, 10, 11, and 23; Yellow- Routes 3 and 4, Mt. Moon; Gold- Union Cave, Mt. Moon; Silver- Goldenrod Game Corner; Crystal- Routes 3 and 4, Union Cave, Mt. Moon; RS/ORAS- Routes 111 and 113; Emerald- Route 111, Mirage Tower; LG- Routes 4, 8, 9, 10, 11, and 23; DPPt- Wayward Cave; HG- Union Cave, Mt. Moon, Safari Zone; SS- Safari Zone, Goldenrod Game Corner; BW- Breed; BW2- Desert Resort, Relic Castle; XY- Friend Safari (Ground)',
	'Sandslash':' Red/FR- Trade; Blue- Route 23, Cerulean Cave; Yellow- Cerulean Cave; Gold- Routes 26 and 27, Mt. Moon; Silver/RSE/ORAS- Evolve Sandshrew; Crystal- Route 26 and Victory Road; LG- Route 23 and Victory Road; DPPt- Route 228; HG- Routes 26 and 27, Safari Zone, Mt. Moon; SS- Safari Zone; BW- Relic Castle; BW2- Route 15, Relic Castle; XY- Route 18, Terminus Cave', 
	'Nidoran-F':' RB- Route 22, Safari Zone, Trade Nidoran-M on Route 5; Yellow- Routes 2, 9, 10, and 22, Safari Zone; GS- Routes 35 and 36; Crystal- Route 35, National Park; RSE/Black/ORAS- Trade; FR- Route 3, Safari Zone, Trade Nidoran-M on Route 5; LG- Route 3, Safari Zone; DPPt- Route 201; HGSS- Routes 35 and 36, Safari Zone; White- White Forest; BW2- Route 2 Hidden Grotto; XY- Route 11',
	'Nidorina':' Red- Safari Zone, Rocket Game Corner, Trade Nidorino on Route 11; Blue- Safari Zone, Trade Nidorino on Route 11; Yellow- Routes 9 and 23, Safari Zone; GSC- Routes 13, 14, and 15; RSE/Black/ORAS- Trade; FR- Safari Zone, Trade Nidorino on Route 11; LG- Safari Zone; DP- Route 221, Valor Lakefront; Pt- Route 221; HGSS- Route 15, Safari Zone; W/BW2- Evolve Nidoran-F; XY- Route 11',
	'Nidoqueen':' RBY/GSC/FRLG/DPPt/HGSS/W/BW2/XY- Evolve Nidorina; RSE/Black/ORAS- Trade',
	'Nidoran-M':' RB- Route 22, Safari Zone; Yellow- Routes 2, 9, 10, and 22, Safari Zone; GS- Routes 35 and 36; Crystal- Route 35, National Park; RSE/Black/ORAS- Trade; FR- Route 3, Safari Zone; LG- Route 3, Safari Zone, Trade Nidoran♀ on Route 5; DPPt- Route 201; HGSS- Routes 35 and 36, Safari Zone; White- White Forest; BW2- Route 2 Hidden Grotto; XY- Route 11',
	'Glaceon':' Evolve Eevee',
	'Sandile':' Relic Castle Grass 40%, Route 4 Grass 35%',
	'Krokorok':' Relic Castle Maze Grass 10%',
	'Krookodile':' Evolve Krokorok',
	'Basculin':' Water',
	'Darumaka':' Route 4 Grass 35%',
	'Darmanitan':' Evolve Darumaka',
	'Trubbish':' Route 4 Grass 25%, Routes 5 & 16 Grass & Dark Grass 20%',
	'Garbodor':' Route 9 Grass & Dark Grass 15%',
	'Minccino':' Routes 5, 9, & 16 Grass & Dark Grass 30%',
	'Cinccino':' Routes 5, 9, & 16 Shaking Grass 5%',
	'Rufflet':' Trade Required',
	'Braviary':' Trade Required',
	'Vullaby':' Route 23 Grass & Dark Grass 5%',
	'Mandibuzz':' Route 4 Thursday',
	'Sandslash':' Relic Castle Grass 20%',
	'Sandslash':' Route 15 Grass & Dark Grass 30%',
	'Dwebble':' Desert Resort Grass 10%',
	'Crustle':' Route 18 Grass & Dark Grass 20%',
	'Scraggy':' Desert Resort Grass 10%',
	'Scrafty':' Route 18 Grass & Dark Grass 30%',
	'Maractus':' Desert Resort Grass 10%',
	'Sigilyph':' Desert Resort Grass 10%',
	'Trapinch':' Reversal Mountain Outside Grass 15%',
	'Vibrava':' Reversal Mountain Outside Dark Grass 5%',
	'Flygon':' Evolve Vibrava',
	'Yamask':' Relic Castle Grass 40%',
	'Cofagrigus':' Evolve Yamask',
	'Tirtouga':' Revive Fossil',
	'Carracosta':' Evolve Tirtouga',
	'Archen':' Revive Fossil',
	'Archeops':' Evolve Archen',
	'Klink':' Chargestone Cave Grass 24%',
	'Klang':' P2 Laboratory Grass 15%',
	'Klinklang':' P2 Laboratory Shaking Grass 5%',
	'Budew':' Breed Roselia',
	'Roselia':' Victory Road Forest Grass & Dark Grass 30%',
	'Roserade':' Route 12, Lostorn & Victory Road Forests Shaking Grass 5%',
	'Gothita':' Routes 5 & 16 Grass & Dark Grass 30%',
	'Gothorita':' Route 9 Grass & Dark Grass 25%',
	'Gothitelle':' Route 9 Shaking Grass 5%',
	'Solosis':' Trade Required',
	'Duosion':' Trade Required',
	'Reuniclus':' Trade Required',
	'Combee':' Route 12 Grass & Dark Grass 20%',
	'Vespiquen':' Route 12 & Lostlorn Forest Shaking Grass 5%',
	'Emolga':' Shaking Grass',
	'Heracross':' Route 12 Grass & Dark Grass 15%',
	'Pinsir':' Lostlorn Forest Hidden Grotto',
	'Blitzle':' Breed Zebstrika',
	'Zebstrika':' Route 7 Grass & Dark Grass 20%',
	'Buizel':' Routes 11, 14, & 23 Surf Rippling Water 60%',
	'Floatzel':' Routes 11, 14, 23 & Lostlorn Forest Surf Rippling Water 10%',
	'Zorua':' Driftveil City (Gift)',
	'Zoroark':' Evolve Zorua',
	'Ducklett':' Driftveil Drawbridge Shadowed Areas 100%',
	'Swanna':' Marvelous Bridge Shadowed Areas 100%',
	'Karrablast':' Routes 6, 8, & 11 Grass & Dark Grass 5%',
	'Escavalier':' Evolve Karrablast',
	'Shelmet':' Routes 6, 8, & 11 Grass & Dark Grass 25%',
	'Accelgor':' Evolve Shelmet',
	'Deerling':' Route 6 Grass & Dark Grass 30%, Route 7 Grass & Dark Grass 20%',
	'Sawsbuck':' Dragonspiral Tower Grass & Dark Grass 35%',
	'Foongus':' Route 6 Grass & Dark Grass 10%',
	'Amoonguss':' Route 22 Grass & Dark Grass 20%',
	'Castform':' Route 6 Shaking Grass 5%',
	'Nosepass':' Clay Tunnel & Underground Ruins Grass 15%',
	'Probopass':' Evolve Nosepass',
	'Aron':' Mistralton Cave Grass 20%',
	'Lairon':' Clay Tunnel & Underground Ruins Grass 15%',
	'Aggron':' Evolve Lairon',
	'Baltoy':' Relic Castle Maze Grass 100%',
	'Claydol':' Evolve Baltoy',
	'Larvesta':' Breed Volcarona',
	'Volcarona':' Relic Castle Maze End',
	'Joltik':' Chargestone Cave Grass 39%',
	'Galvantula':' Evolve Joltik',
	'Ferroseed':' Chargestone Cave Grass 20%',
	'Ferrothorn':' Evolve Ferroseed',
	'Tynamo':' Chargestone Cave Grass 2%, Seaside Cave Grass 8%',
	'Eelektrik':' Seaside Cave Grass 5%',
	'Eelektross':' Evolve Eelektrik',
	'Frillish':' Routes 4, 17, & 18 Surf 100%, Virbank City Surf 100%',
	'Jellicent':' Undella Bay Surf Rippling Water 60%, Humilau City & Route 21 Surf Rippling Water 60%',
	'Alomomola':' Routes 4, 17, & 18 Surf Rippling Water 95%',
	'Axew':' Mistralton Cave Grass 20%',
	'Fraxure':' Nature Preserve Grass & Dark Grass 10%',
	'Haxorus':' Nature Preserve',
	'Zangoose':' Village Bridge Grass & Dark Grass 15%',
	'Seviper':' Route 11 Grass & Dark Grass 10%, Village Bridge Grass & Dark Grass 15%',
	'Elgyem':' Celestial Tower 4F Grss 40%',
	'Beheeyem':' Evolve Elgyem',
	'Litwick':' Celestial Tower 1F Grass 100%',
	'Lampent':' Evolve Litwick',
	'Chandelure':' Evolve Lampent',
	'Heatmor':' Twist Mountain Grass Summer 20%',
	'Durant':' Clay Tunnel & Underground Ruins Grass 20%',
	'Cubchoo':' Route 7 Grass & Dark Grass Winter 25%',
	'Beartic':' Twist Mountain Grass Winter 20%',
	'Cryogonal':' Twist Mountain Grass Winter 15%',
	'Tornadus':' Trade Required',
	'Thundurus':' Trade Required',
	'Landorus':' Trade Required',
	'Skorupi':' Reversal Mountain Outside Grass & Dark Grass 30%',
	'Drapion':' Evolve Skorupi',
	'Skarmory':' Reversal Mountain Outside Dark Grass 15%',
	'Numel':' Trade Required',
	'Camerupt':' Trade Required',
	'Spoink':' Reversal Mountain Grass 30%',
	'Grumpig':' Reversal Mountain Outside Dark Grass 30%',
	'Drifloon':' Route 13 Hidden Grotto',
	'Drifblim':' Reversal Mountain Outside Grass & Dark Grass 20%',
	'Shuppet':' Breed Banette',
	'Banette':' Victory Road Grass 70%',
	'Wingull':' Breed Pelipper',
	'Pelipper':' Route 13 Grass & Dark Grass 25%',
	'Lunatone':' Routes 13 & 22 Grass & Dark Grass 10%',
	'Solrock':' Routes 13 & 22 Grass & Dark Grass  10%',
	'Absol':' Routes 13 & 14 Grass & Dark Grass 15%',
	'Tangela':' Giant Chasm Outside Grass & Dark Grass 30%',
	'Tangrowth':' Route 13 Shaking Grass 5%, Giant Chasm Outside Shaking Grass 5%',
	'Mienfoo':' Route 14 Double Grass 30%, Route 22 Grass & Dark Grass 25%',
	'Mienshao':' Dragonspiral Tower Outside Grass & Dark Grass 25%',
	'Gligar':' Route 15 Grass & Dark Grass 25%',
	'Gliscor':' Routes 11, 15, & 23 Shaking Grass 5%',
	'Pawniard':' Route 9 Grass & Dark Grass 15%',
	'Bisharp':' Evolve Pawniard',
	'Cobalion':' Route 13',
	'Terrakion':' Route 22',
	'Virizion':' Route 11',
	'Tympole':' Breed Palpitoad',
	'Palpitoad':' Route 8 & Moor of Icirrus Grass 40%',
	'Seismitoad':' Route 8 & Moor of Icirrus Surf Rippling Water 5%',
	'Stunfisk':' Icirrus City & Moor of Icirrus Surf 100%',
	'Shuckle':' Seaside Cave Grass 5%',
	'Mantyke':' Undella Bay Surf 30%',
	'Mantine':' Undella Bay Surf Rippling Water 5%',
	'Remoraid':' Route 21 Fish Rippling Water 65%, Undella Bay Fish Rippling Water 60%',
	'Octillery':' Undella Bay & Route 21 Fish Rippling Water 5%',
	'Corsola':' Humilau City Surf Rippling Water 30%',
	'Staryu':' Undella Town & Route 13 Surf Rippling Water 60%',
	'Starmie':' Route 13, Undella Town, & Humilau City Surf Rippling Water 5%',
	'Wailmer':' Undella Bay Surf Rippling Water Winter 60%, Undella Bay Surf Rippling Water Spring, Summer, & Autumn 30%',
	'Wailord':' Undella Bay Surf Rippling Water 5%',
	'Lapras':' Village Bridge Surf Rippling Water 5%',
	'Spheal':' Undella Bay Surf Winter 30%',
	'Sealeo':' Undella Bay Surf Rippling Water Winter 30%',
	'Walrein':' Undella Bay Surf Rippling Water Winter 5%',
	'Swablu':' Route 15 & Abundant Shrine Grass 20%',
	'Altaria':' Victory Road Outside & Nature Preserve Grass & Dark Grass 20%',
	'Bronzor':' Abundant Shrine Grass 15%',
	'Bronzong':' Abundant Shrine Dark Grass 10%',
	'Sneasel':' Giant Chasm Grass 20%',
	'Weavile':' Evolve Sneasel',
	'Delibird':' Giant Chasm & Route 22 Grass & Dark Grass 5%',
	'Vanillite':' Breed Vanillish',
	'Vanillish':' Dragonspiral Tower Grass & Dark Grass Winter 25%',
	'Vanilluxe':' Dragonspiral Tower & Giant Chasm Shaking Grass 5%',
	'Swinub':' Breed Piloswine',
	'Piloswine':' Giant Chasm Grass & Dark Grass 30%',
	'Mamoswine':' Giant Chasm Shaking Grass 5%',
	'Ditto':' Giant Chasm Grass & Dark Grass 15%',
	'Beldum':' Breed Beldum',
	'Metang':' Giant Chasm Grass & Dark Grass 10%',
	'Metagross':' Giant Chasm Shaking Grass 5%',
	'Seel':' Giant Chasm Cave Surf Rippling Water 60%',
	'Dewgong':' Giant Chasm & Seaside Cave Surf Rippling Water 10%',
	'Throh':' Victory Road Cliffside Grass & Dark Grass 30%',
	'Sawk':' Route 23 Grass & Dark Grass 25%',
	'Bouffalant':' Route 23 Grass & Dark Grass 35%',
	'Druddigon':' Victory Road 7F & N\'s Castle Entrance Grass 80%',
	'Golett':' Breed Golurk',
	'Golurk':' Dragonspiral Tower 2F Grass 100%',
	'Deino':' Breed Zweilous',
	'Zweilous':' Victory Road & N\'s Castle Entrance Grass 20%',
	'Hydreigon':' Evolve Zweilous',
	'Slakoth':' Breed Vigoroth',
	'Vigoroth':' Pinwheel Forest Grass & Dark Grass 15%',
	'Slaking':' Pinwheel Forest Shaking Grass 5%',
	'Corphish':' Route 3 Surf Rippling Water 60%',
	'Crawdaunt':' Route 3 & Striaton City Surf Rippling Water 10%',
	'Igglybuff':' Breed Igglybuff',
	'Lickitung':' Route 2 Grass 10%',
	'Lickilicky':' Route 2 Shaking Grass 5%',
	'Yanma':' Route 3 Grass & Double Grass 10%',
	'Yanmega':' Route 3 Shaking Grass 5%',
	'Tropius':' Route 18 Grass & Double Grass 10%',
	'Carnivine':' Route 18 Grass & Double Grass 10%',
	'Croagunk':' Route 8, Icirrus City, & Moor of Icirrus Grass 15%',
	'Toxicroat':' Pinwheel Forest Grass & Double Grass 10%',
	'Larvitar':' Breed Pupitar',
	'Pupitar':' Route 15 Grass & Double Grass 15%',
	'Tyranitar':' Route 15 Shaking Grass 5%',
	'Reshiram':' Trade Required',
	'Zekrom':' Dragonspiral Tower',
	'Kyurem':' Giant Chasm'
    };
        
    $('.Pokemon').keypress(function(event){
        if(event.which == 13){
            $('.go').click();
        }
    });
    
    $('.go').click(function(){
        var poke = $('.Pokemon').val();
        var hp = ($('.hp').val() && $('.hp').val() !== '0' ? ' Level up holding Power Weight against Stunfisk for a total of 6 HP EVs per level. Level up holding Power Weight against Victini for a total of 7 HP EVs per level.' : ''); 
        var attack = ($('.atk').val() && $('.atk').val() !== '0' ? ' Level up holding Power Bracer against Tranquill, Sawsbuck, Druddigon, or Beartic for a total of 6 Attack EVs per level. Level up holding Power Bracer against Patrat, Lillipup, Mienfoo, or Golett for a total of 5 Attack EVs per level.': '');
        var defense = ($('.def').val() && $('def').val() !== '0' ? ' Level up holding Power Belt against Roggenrola, Onix, Sewaddle, or Venipede for a total of 5 Defense EVs per level. Level up holding Power Belt against Sandslash or Cofagrigus for a total of 6 Defense EVs per level.': '');
        var spattack = ($('.spatk').val() && $('.spatk').val() !== '0' ? ' Level up holding Power Lens against Litwick or Elgyem for a total of 5 Special Attack EVs per level. ': '');
        var spdefense = ($('.spdef').val() && $('.spdef').val() !== '0' ? ' Level up holding Power Band against Frillish for a total of 5 Special Defense EVs per level. Level up holding Power Band against Claydol for a total of 6 Special Defense EVs per level. ': '');
        var speed = ($('.spe').val() && $('.spe').val() !== '0' ? ' Level up holding Power Anklet against Basculin for a total of 5 Speed EVs per level.': '');
        
	var moveRespOne,
		moveRespTwo,
		moveRespThree,
		moveRespFour,
		learnable = [];
		
	var xhr = new XMLHttpRequest();
	xhr.open('GET', 'http://pokeapi.co/api/v1/pokemon/' + poke.toLowerCase() + '/', false);
	xhr.send(null);
	var parse = JSON.parse(xhr.responseText);

	if(moves[$('.move-1 :selected').text()] !== undefined){
		moveRespOne = moves[$('.move-1 :selected').text()];
	} else {
		moveRespOne = 'If your Pokemon doesn\'t learn this by level 100 or by <a href="http://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Egg_Group">breeding</a>, it ain\'t going to';
	}
	
	if(moves[$('.move-2 :selected').text()] !== undefined){
		moveRespTwo = moves[$('.move-2 :selected').text()];
	} else {
		moveRespTwo = 'If your Pokemon doesn\'t learn this by level 100 or by <a href="http://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Egg_Group">breeding</a>, it ain\'t going to';
	}
	
	if(moves[$('.move-3 :selected').text()] !== undefined){
		moveRespThree = moves[$('.move-3 :selected').text()];
	} else {
		moveRespThree = 'If your Pokemon doesn\'t learn this by level 100 or by <a href="http://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Egg_Group">breeding</a>, it ain\'t going to';
	}
	
	if(moves[$('.move-4 :selected').text()] !== undefined){
		moveRespFour = moves[$('.move-4 :selected').text()];
	} else {
		moveRespFour = 'If your Pokemon doesn\'t learn this by level 100 or by <a href="http://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Egg_Group">breeding</a>, it ain\'t going to';
	}
        
        $('.result-container').html('<span class="result">How to breed the perfect ' + poke + '!</span>' +
        '<p class="moveinfo">' + poke + ': ' + locations[poke] + '</p>' +
        '<p class="moveinfo">' + $('.item :selected').text() +': ' + items[$('.item :selected').text()] + '</p>' +
        '<p class="moveinfo">EVs: ' + hp + attack + defense + spattack + spdefense + speed + '</p>' +
        '<p class="moveinfo">' + $('.nature :selected').text() + ' Nature: Breed with a ' + $('.nature :selected').text() + ' nature Ditto holding an Everstone </p>' +
        '<p class="moveinfo">' + $('.move-1 :selected').text() + ': ' + moveRespOne + '</p>' +
        '<p class="moveinfo">' + $('.move-2 :selected').text() + ': ' + moveRespTwo + '</p>' +
        '<p class="moveinfo">' + $('.move-3 :selected').text() + ': ' + moveRespThree + '</p>' +
        '<p class="moveinfo">' + $('.move-4 :selected').text() + ': ' + moveRespFour + '</p>'
        );
  });
				
});
